# title: Hi, It's Huzaifa
# logo: asset/img/cover-pic.png
# show_downloads: true
remote_theme: jekyll/minima
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
